# Generated by Django 5.0.6 on 2024-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_email',
            field=models.BooleanField(default=True, help_text='Могут ли с вами связаться по почтовому адресу', verbose_name='Открытость почтового адреса'),
        ),
    ]
