# Generated by Django 5.0.6 on 2024-08-06 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_payment', models.DateTimeField(auto_now_add=True, verbose_name='дата оплаты')),
                ('price', models.PositiveIntegerField(verbose_name='сумма оплаты')),
                ('session_id', models.CharField(max_length=300, verbose_name=' id сессии')),
                ('link', models.URLField(max_length=400, verbose_name='Ссылка на оплату')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
