# Generated by Django 5.0.6 on 2024-08-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='link',
        ),
    ]
