# Generated by Django 5.0.6 on 2024-08-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_payment_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='datetime_payment',
        ),
    ]
