# Generated by Django 5.0.6 on 2024-08-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='open_email',
            field=models.BooleanField(default=True, verbose_name='Могут ли с вами связаться по почтовому адресу'),
        ),
    ]
