# Generated by Django 5.0.6 on 2024-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publication/images', verbose_name='изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='название публикации')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='publication/preview', verbose_name='превью')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Ссылка')),
                ('images', models.ManyToManyField(to='main_app.image', verbose_name='изображения')),
            ],
        ),
    ]
