# Generated by Django 5.0.6 on 2024-08-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписка активна до'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна ли подписка'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='День обновления подписки'),
        ),
    ]
