# Generated by Django 5.0.6 on 2024-08-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_publication_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='content',
            field=models.TextField(default='some huge text', verbose_name='содержание публикации'),
            preserve_default=False,
        ),
    ]
