# Generated by Django 5.0.6 on 2024-08-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_publication_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'публикация', 'verbose_name_plural': 'публикации'},
        ),
    ]
