# Generated by Django 5.0.6 on 2024-08-05 13:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_publication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='содержание публикации'),
        ),
    ]
