# Generated by Django 5.0.6 on 2024-08-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_publication_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(default='description ula-ula-e-e-e', verbose_name='Краткое описание публикации'),
            preserve_default=False,
        ),
    ]
