# Generated by Django 5.0.6 on 2024-08-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_publication_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
