# Generated by Django 5.0.6 on 2024-08-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_publication_images_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='active_until',
            new_name='end_at',
        ),
    ]
