# Generated by Django 5.0.6 on 2024-08-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_subscription_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='owner',
        ),
    ]
